# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 680d66f02d258eb5165b40275eef6ec53067d0bbcf1dbff4071d6cd476ec9acf17d878b9f8de5304a28221d046365fc35c9212ee080f1a27efe9ec279c58d090

test:
  secret_key_base: eb3c5a8a749a0444a3f65fee1f1a72091d21b6c8603646ed032aa64540ca83c00299ff98d6c5ca73b9cab78206d55aa99fb3c2c637cf244b9b0675ba6c58dd84

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
